
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - siang-test.siang-test.com
  resources:
  - outloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - siang-test.siang-test.com
  resources:
  - outloadbalancers/finalizers
  verbs:
  - update
- apiGroups:
  - siang-test.siang-test.com
  resources:
  - outloadbalancers/status
  verbs:
  - get
  - patch
  - update
